package io.github.morphling.jpa.processor;

import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Generates a {@code <Entity>Fields} interface (in the entity's package) of
 * dotted-path {@code String} constants for every persistent attribute and
 * association, so conditions can be written as
 * {@code @Select(value = UserFields.dept.name)} with IDE auto-completion.
 * Recursion into associations is cycle-guarded and depth-limited.
 *
 * @author anyifei
 */
final class FieldsGeneration {

    private static final int MAX_DEPTH = 4;

    private final Elements elements;
    private final Filer filer;
    private final Messager messager;
    private final EntityModel model;

    FieldsGeneration(ProcessingEnvironment env) {
        this.elements = env.getElementUtils();
        this.filer = env.getFiler();
        this.messager = env.getMessager();
        this.model = new EntityModel(env);
    }

    void generate(TypeElement entity) throws IOException {
        String simpleName = entity.getSimpleName() + "Fields";
        String pkg = elements.getPackageOf(entity).getQualifiedName().toString();
        String fqn = pkg.isEmpty() ? simpleName : pkg + "." + simpleName;

        if (elements.getTypeElement(fqn) != null) {
            messager.printMessage(Diagnostic.Kind.WARNING,
                    "@EntityCondition: " + fqn + " already exists; skipping generated field constants for "
                            + entity.getQualifiedName(), entity);
            return;
        }

        StringBuilder sb = new StringBuilder();
        if (!pkg.isEmpty()) {
            sb.append("package ").append(pkg).append(";\n\n");
        }
        sb.append("/** Auto-generated by jpa-specification-helper: dotted path constants for ")
                .append(entity.getQualifiedName()).append(".\n")
                .append(" * Use them in @Select(value = ...) for IDE auto-completion and refactor safety. */\n");
        sb.append("public interface ").append(simpleName).append(" {\n");
        Set<String> chain = new LinkedHashSet<>();
        chain.add(entity.getQualifiedName().toString());
        emit(entity, "", chain, 0, "    ", sb);
        sb.append("}\n");

        JavaFileObject file = filer.createSourceFile(fqn);
        try (Writer writer = file.openWriter()) {
            writer.write(sb.toString());
        }
    }

    private void emit(TypeElement entity, String prefix, Set<String> chain, int depth, String indent, StringBuilder sb) {
        for (Element field : model.persistentFields(entity)) {
            String name = field.getSimpleName().toString();
            String path = prefix.isEmpty() ? name : prefix + "." + name;
            if (model.isAssociation(field)) {
                TypeElement target = model.navigate(entity, field);
                if (target == null || chain.contains(target.getQualifiedName().toString()) || depth >= MAX_DEPTH) {
                    sb.append(indent).append("String ").append(name).append(" = \"").append(path).append("\";\n");
                } else {
                    sb.append(indent).append("interface ").append(name).append(" {\n");
                    Set<String> next = new LinkedHashSet<>(chain);
                    next.add(target.getQualifiedName().toString());
                    emit(target, path, next, depth + 1, indent + "    ", sb);
                    sb.append(indent).append("}\n");
                }
            } else if (!model.isEmbedded(field)) {
                // @Embedded fields are skipped: the runtime (plain string paths) cannot navigate them.
                sb.append(indent).append("String ").append(name).append(" = \"").append(path).append("\";\n");
            }
        }
    }
}
